# cloudbuild.yaml
steps:
# Step 1: Install dependencies
- name: 'python:3.11'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      echo "Installing dependencies..."
      pip install -r requirements.txt || echo "No requirements.txt, skipping"

# Step 2: Run tests
- name: 'python:3.11'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      echo "Running tests..."
      if [ -d "tests" ]; then
        pytest tests/ || echo "Tests failed"
      else
        echo "No tests folder, skipping"
      fi

# Step 3: Optional deploy example
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      echo "Deploy step (example)"
      # gcloud app deploy --quiet

options:
  logging: CLOUD_LOGGING_ONLY
